[project]
name = "debugger-demo"
authors = []
description = ""
telemetry = true

[contracts.bar]
path = "contracts/bar.clar"

[contracts.baz]
path = "contracts/baz.clar"

[contracts.foo]
path = "contracts/foo.clar"
